// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Trip
{
    public int Id { get; set; }

    public int? PickUpLocationId { get; set; }

    public int? DropOffLocationId { get; set; }

    public int? MaxPerson { get; set; }

    public int? MinPerson { get; set; }

    public DateOnly? BookingDate { get; set; }

    public TimeOnly? HourInDay { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Location DropOffLocation { get; set; }

    public virtual Location PickUpLocation { get; set; }
}